### PR TITLE
#164814083 Consume update profile picture endpoint

### PR DESCRIPTION
**Pull request by misocho**
#### What does this PR do?
Consume the upload profile picture endpoint
#### Description of Task to be completed?
Allow a user to upload profile picture form local storage
#### How should this be manually tested?
* Clone the repo
* Navigate to project directory
* Open signup.html with your browser 
* Navigate to the profile page
* Click on the edit icon 
* Upload a picture from local storage
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#164814083
#### Screenshots (if appropriate)
image
image

#### Questions:
N/A

### CODE REVIEW

**Comment by bencyn** [comment]
Looks good on my local environment. You can try to clear the errors on code quality

**Review by misocho — COMMENTED** [review]
Errors cleared on code quality @bencyn

**Review by Tevinthuku — COMMENTED** [review]
The upload feature works seamlessly. Awesome work. Since the `profile.js` file works on the `profile page` you can add it to the `js/pages` directory so that the js files are more organised. Besides that everything else is good :+1:

**Review by martinMutuma — COMMENTED** [review]
The Url still points to the old Hosted app
Please consider refactoring

**Review by misocho — COMMENTED** [review]
Made the necessary changes @martinMutuma

**Review by Tevinthuku — CHANGES_REQUESTED** [review]
@misocho You have removed the `profile.js` file from where it was but you haven't added it to where its meant to be in the `js/pages` dir so the response to the file request is a `404`

image

**Comment by martinMutuma** [comment]
Can't upload when I clone it offline

**Review by martinMutuma — APPROVED** [review]
Works on my side

**Comment by misocho** [comment]
@martinMutuma Sorry, that was an error on my part. It should work now.

**Review by Tevinthuku — APPROVED** [review]

**Pull request merged**
