### PR TITLE
164750161 fix response messages

### PR DESCRIPTION
**Pull request by ceexon**
#### What does this PR do?
Contains an update on `api/v2` response messages on success

#### Description of the Tasks to be accomplished
  -  update on user responses when they successfully perform actions eg. signup and login 
#### How should this be manually tested?
Clone this repo
`$ git clone https://github.com/martinMutuma/def-politico.git`

CD into the project directory
`$ cd def-politico`

Check out the branch for this PR
`$ git checkout bg/164750161-fix-response-messages `

Activate the virtual environment
`$ source env/bin/activate `

Setup the environment variables
`$ source .env `

Run the app
`$ python run.py `

Test the app
`$ python3 -m pytest`

#### What are the relevant pivotal tracker stories?
[#164750161](https://www.pivotaltracker.com/story/show/164750161)

### CODE REVIEW

**Review by misocho — APPROVED** [review]
looks good

**Review by justMuriithi — APPROVED** [review]
Good job. Now the unique responses show what was successful after the removal of the generic Success message. Good to go

**Review by martinMutuma — APPROVED** [review]
Looks okay

**Review by martinMutuma — CHANGES_REQUESTED** [review]
please fix the failing tests

**Pull request merged**
