### PR TITLE
#164813006- update Readme

### PR DESCRIPTION
**Pull request by martinMutuma**
#### What does this PR do?
Update ReadMe

#### Description of the Tasks to be accomplished
Update Readme to reflect changes and updates made

#### How should this be manually tested?
Clone this repo
`$ git clone https://github.com/martinMutuma/def-politico.git`
CD into the project directory
`$ cd def-politico`
Check out the branch for this PR
`$ git checkout ch/164813006-update-readme
Activate the virtual environment
`$ source venv/bin/activate `
Setup the environment variables
`$ source .env `
Run the app
open Readme.md file to view changes 

#### What are the relevant pivotal tracker stories?
[#164813006](https://www.pivotaltracker.com/story/show/164813006)

#### Screenshots
N/A

### CODE REVIEW

**Review by misocho — APPROVED** [review]

**Review by Tevinthuku — APPROVED** [review]
:+1: I think this can now be merged

**Comment by bencyn** [comment]
Hello kindly add this endpoint `/api/v2/auth/update`  that updates a user profile

**Comment by martinMutuma** [comment]
> Hello kindly add this endpoint `/api/v2/auth/update` that updates a user profile

Added

**Review by justMuriithi — APPROVED** [review]
With the redirects now leading to our new hosting link, I believe we are set

**Pull request merged**
