### PR TITLE
#164786590 update user endpoint

### PR DESCRIPTION
**Pull request by bencyn**
#### What does this PR do?
This PR allows a user to update his/her profile

#### Description of the Tasks to be accomplished
  -  write test for update user endpoint
  - add update user endpoint`

#### How should this be manually tested?
Clone this repo
`$ git clone https://github.com/martinMutuma/def-politico.git`

CD into the project directory
`$ cd def-politico`

Check out the branch for this PR
`$ git checkout ft/164786590-update-user-endpoint`

Activate the virtual environment
`$ source env/bin/activate `

Setup the environment variables
`$ source .env `

Run the app
`$ python run.py `

#### What are the relevant pivotal tracker stories?
[#164786590](https://www.pivotaltracker.com/story/show/164786590)

#### Screenshots

Screenshot from 2019-03-21 01-30-38

### CODE REVIEW

**Comment by justMuriithi** [comment]
I notice codacy has raised a number of trailing whitespace issues. Might I suggest you use flake8 to help you capture this from your text editor of choice
https://pypi.org/project/flake8/

**Review by justMuriithi — COMMENTED** [review]
I notice codacy has raised a number of trailing whitespace issues. Might I suggest you use flake8 to help you capture this from your text editor of choice
https://pypi.org/project/flake8/

**Review by misocho — APPROVED** [review]
Looks good

**Review by Tevinthuku — APPROVED** [review]

**Review by justMuriithi — APPROVED** [review]
Looks like we are now good to go

**Pull request merged**
