### PR TITLE
#164793128 Allow user to upload profile picture

### PR DESCRIPTION
**Pull request by misocho**
#### What does this PR do?
Allow a user to update profile picture
#### Description of Task to be completed?
Allow a user to update profile picture
#### How should this be manually tested?
* Clone the repo
`
$ git clone https://github.com/martinMutuma/def-politico.git
`
* Navigate to project directory
* Create and activate a virtual environment
* Branch to `ft/164793128-api-upload-image`
* Install requirements
`
pip install requirements.txt
`
* Setup environment variables
* Run `flask run.py`
* Run `pytest` to test the endpoints
* Run Postman and test the `PATCH` endpoint `/api/v2/user/update_image`
* Required fields
```
'url' : `image url`
```
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#164793128
#### Screenshots (if appropriate)
image

#### Questions:
N/A

### CODE REVIEW

**Review by justMuriithi — COMMENTED** [review]
I notice codacy has raised a number of trailing whitespace issues. Might I suggest you use flake8 to help you capture this from your text editor of choice. flake8 will also show you the unused imports within your code editor making it easy for you to refactor your code.
https://pypi.org/project/flake8/

**Comment by misocho** [comment]
@justMuriithi Made the necessary changes, please review.

**Review by justMuriithi — APPROVED** [review]
Good work implementing the linting changes. The PR is ready

**Review by martinMutuma — APPROVED** [review]
Looks good

**Review by Tevinthuku — COMMENTED** [review]
It all works as expected :+1:

**Pull request merged**
